spring:
  application:
    name: app-kubernetes-demo

  datasource:
    url: jdbc:postgresql://postgres:5432/mydb
    username: user
    password: password
  rabbitmq:
    host: rabbitmq
    port: 5672
  jpa:
    hibernate:
      ddl-auto: update
